version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: express-server
    volumes:
      - mongodb:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped
volumes:
  mongodb: {}
